### ISSUE TITLE
Can not run the code with use_quantize_model = True

### ISSUE THREAD

**Issue by zenghao-zh** [thu-ml/Jetfire-INT8Training#1]
Dear authors:

I run train.py with quantize model in shakespeare_char config, but it reported 

File ".....INT8_GPT2/../Jetfire/Linear/linear_bwd.py", line 11, in int8_linear_backward
    SG16T = SG16.t().contiguous()
RuntimeError: CUDA error: an illegal memory access was encountered

there may be some bugs. Could you help to fix them?

**Comment by qingswu** [comment]
the same ilegal access error happens on my side, could you share your way to fix it? @zenghao-zh 
or your dev environment

**Comment by jerryw95** [comment]
Encountered with the same problem. Have you solved it yet?

> the same ilegal access error happens on my side, could you share your way to fix it? [@zenghao-zh](https://github.com/zenghao-zh) or your dev environment
